### ISSUE TITLE
[FEAT] 버전관리 Kotlin DSL 방식으로 변경

### ISSUE THREAD

**Issue by KkamSonLee** [Meetiing/MeetiingClone#44]
## 🔈 Issue

- Dependency 관리가 까다로워서 BuildSrc 이용해서 바꿔놓으려 합니다.

## 📑 To-do

- [x] BuildSrc Dir생성
- [x] Version 클래스 생성
- [x] Dependency 클래스 생성
- [x] Dependency Ext 클래스 생성
- [x] app 수준 gradle에 삽입
