### ISSUE TITLE
[FIX] 유의사항, 닉네임, 성별, 생년월일 부분 ui 깨짐 수정

### ISSUE THREAD

**Issue by DAEHYEONJO** [Meetiing/MeetiingClone#47]
## 🔈 Issue
![image](https://user-images.githubusercontent.com/68371979/207061794-e696907e-420b-4d82-9002-1aa7fa42473a.png)
* 이부분 기기 사이즈 변경시 ui 깨짐현상 발생함

## 📑 To-do
- [ ] 유의사항 view ui 수정
- [ ] 닉네임 view ui 수정
- [ ] 성별 view ui 수정
- [ ] 생년월일 view ui 수정
